<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>cda15aa0-e234-4888-b095-c11159cd60e9</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" Version="1.73.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.73.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Shared\Infomatrix.Contracts\AI\*.cs" Link="Contracts\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
