<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.3" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.AzureOpenAI" Version="1.73.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.73.0" />
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
     <PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />
	  <PackageReference Include="Supabase" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infomatrix.Core.Application\Infomatrix.Core.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Shared\Infomatrix.Contracts\AI\*.cs" Link="Contracts\%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
