<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Shared\**" />
    <EmbeddedResource Remove="Shared\**" />
    <None Remove="Shared\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infomatrix.Core.Domain\Infomatrix.Core.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
    <PackageReference Include="Scrutor" Version="7.0.0" />
  </ItemGroup>

</Project>
